package com.ismailmushraf.bujo.fragments;

import android.app.Dialog; import android.os.Bundle; import android.view.*; import android.widget.*;
import androidx.annotation.NonNull; import androidx.fragment.app.DialogFragment;
import com.ismailmushraf.bujo.R; import com.ismailmushraf.bujo.coach.*; import com.ismailmushraf.bujo.db.DatabaseManager; import com.ismailmushraf.bujo.models.*;
import org.json.*; import java.util.*;

/** The coach is deliberately a short Plan Day flow, not a destination screen. */
public final class CoachWizardDialog extends DialogFragment {
  private View root; private int step=0; private final ArrayList<JSONObject> suggestions=new ArrayList<>();
  public static void show(androidx.fragment.app.FragmentManager manager) { if(manager.findFragmentByTag("coach_wizard")==null) new CoachWizardDialog().show(manager,"coach_wizard"); }
  @NonNull @Override public Dialog onCreateDialog(Bundle state) { root=LayoutInflater.from(requireContext()).inflate(R.layout.dialog_coach_wizard,null); Dialog d=new android.app.AlertDialog.Builder(requireContext(),R.style.BujoDialog).setView(root).create();
    root.findViewById(R.id.coach_wizard_cancel).setOnClickListener(v->dismiss()); root.findViewById(R.id.coach_wizard_next).setOnClickListener(v->next()); root.findViewById(R.id.coach_wizard_back).setOnClickListener(v->{step--; render();}); root.findViewById(R.id.coach_wizard_add).setOnClickListener(v->addSelected()); render(); return d; }
  private void next(){ if(step<2){ step++; render(); return; } int minutes; try { minutes=Integer.parseInt(((EditText)root.findViewById(R.id.coach_wizard_minutes)).getText().toString()); } catch(Exception e){ minutes=-1; } if(minutes<0||minutes>960){ ((EditText)root.findViewById(R.id.coach_wizard_minutes)).setError(getString(R.string.coach_invalid_minutes)); return; }
    try { JSONObject input=new JSONObject().put("kind","day planning").put("mood",choice(R.id.coach_wizard_mood)).put("energy",choice(R.id.coach_wizard_energy)).put("available_minutes",minutes).put("note",((EditText)root.findViewById(R.id.coach_wizard_note)).getText().toString()); CoachEngine engine=CoachEngine.get(requireContext()); if(!engine.submit(input,true,record->{ if(!isAdded())return; if(record==null){error();return;} try { JSONObject answer=new JSONObject(record.response); JSONArray list=answer.getJSONArray("suggestions"); suggestions.clear(); for(int i=0;i<list.length();i++) suggestions.add(list.getJSONObject(i)); String message=answer.getString("message"); if(!"ai".equals(record.status)) message+="\n\nOffline fallback: "+engine.notice(); showResults(message); } catch(Exception e){ error(); }})){ TextView status=root.findViewById(R.id.coach_wizard_status); status.setText(R.string.coach_busy); status.setVisibility(View.VISIBLE); return; } ((TextView)root.findViewById(R.id.coach_wizard_status)).setText(R.string.coach_working); root.findViewById(R.id.coach_wizard_status).setVisibility(View.VISIBLE); root.findViewById(R.id.coach_wizard_next).setEnabled(false); } catch(Exception e){ error(); } }
  private String choice(int id){ RadioGroup group=root.findViewById(id); RadioButton b=root.findViewById(group.getCheckedRadioButtonId()); return b.getText().toString(); }
  private void error(){ if(!isAdded())return; TextView status=root.findViewById(R.id.coach_wizard_status); status.setText(CoachEngine.get(requireContext()).notice()); status.setVisibility(View.VISIBLE); root.findViewById(R.id.coach_wizard_next).setEnabled(true); }
  private void showResults(String message){ step=3; root.findViewById(R.id.coach_wizard_status).setVisibility(View.GONE); ((TextView)root.findViewById(R.id.coach_wizard_message)).setText(message); LinearLayout list=root.findViewById(R.id.coach_wizard_suggestions); list.removeAllViews(); Map<Integer,String> names=projects(); for(JSONObject item:suggestions){ View row=LayoutInflater.from(requireContext()).inflate(R.layout.item_coach_suggestion,list,false); int id=item.optInt("project_id"); ((TextView)row.findViewById(R.id.coach_suggestion_title)).setText(item.optString("title")); ((TextView)row.findViewById(R.id.coach_suggestion_project)).setText(id==0?"GENERAL":"PROJECT · "+names.get(id)); ((TextView)row.findViewById(R.id.coach_suggestion_reason)).setText(item.optString("reason")); row.setTag(item); row.setOnClickListener(v->{ boolean selected=!Boolean.TRUE.equals(v.getTag(R.id.coach_suggestion_tick)); v.setTag(R.id.coach_suggestion_tick,selected); v.findViewById(R.id.coach_suggestion_tick).setBackgroundResource(selected?R.drawable.bb10_checkbox_checked_bg:R.drawable.bb10_checkbox_unchecked_bg); }); list.addView(row); } if(suggestions.isEmpty()){ TextView none=new TextView(requireContext()); none.setText("No tasks were suggested. You can keep your current plan."); list.addView(none); } render(); }
  private Map<Integer,String> projects(){ Map<Integer,String> map=new HashMap<>(); DatabaseManager db=new DatabaseManager(requireContext()); db.open(); try { for(Project p:db.getAllProjects()) map.put(p.getId(),p.getName()); } finally {db.close();} return map; }
  private void addSelected(){ DatabaseManager db=new DatabaseManager(requireContext()); int count=0; try { Map<Integer,String> names=projects(); ArrayList<Entry> selected=new ArrayList<>(); LinearLayout list=root.findViewById(R.id.coach_wizard_suggestions); for(int i=0;i<list.getChildCount();i++) if(Boolean.TRUE.equals(list.getChildAt(i).getTag(R.id.coach_suggestion_tick))){ JSONObject item=(JSONObject)list.getChildAt(i).getTag(); Entry e=new Entry(); e.setSignifier("*"); e.setContent(item.getString("title")); e.setDeadline(System.currentTimeMillis()); int project=item.optInt("project_id"); if(project!=0){e.setProjectId(project); e.setProjectTag(names.get(project));} selected.add(e); } if(selected.isEmpty()){ Toast.makeText(requireContext(),"Select at least one task.",Toast.LENGTH_SHORT).show(); return; } db.open(); db.insertEntriesAtomically(selected); count=selected.size(); } catch(Exception error) { Toast.makeText(requireContext(),"Could not add the selected tasks. Nothing was changed.",Toast.LENGTH_LONG).show(); return; } finally {db.close();} androidx.fragment.app.Fragment active=getParentFragmentManager().findFragmentById(R.id.fragment_container); if(active instanceof DailyLogFragment) ((DailyLogFragment)active).refreshFromCoach(); Toast.makeText(requireContext(),count+" task"+(count==1?"":"s")+" added to Today",Toast.LENGTH_SHORT).show(); dismiss(); }
  private void render(){ int[] ids={R.id.coach_step_mood,R.id.coach_step_energy,R.id.coach_step_time,R.id.coach_step_results}; for(int i=0;i<ids.length;i++) root.findViewById(ids[i]).setVisibility(i==step?View.VISIBLE:View.GONE); root.findViewById(R.id.coach_wizard_back).setVisibility(step>0&&step<3?View.VISIBLE:View.GONE); root.findViewById(R.id.coach_wizard_next).setVisibility(step<3?View.VISIBLE:View.GONE); root.findViewById(R.id.coach_wizard_add).setVisibility(step==3?View.VISIBLE:View.GONE); }
  @Override public void onStart(){ super.onStart(); if(getDialog()!=null && getDialog().getWindow()!=null){ android.util.DisplayMetrics m=getResources().getDisplayMetrics(); getDialog().getWindow().setLayout((int)(m.widthPixels*.82),(int)(m.heightPixels*.76)); getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE); } }
}
