package com.ismailmushraf.bujo.fragments;

import android.os.Bundle;
import androidx.fragment.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;

import com.ismailmushraf.bujo.MainActivity;
import com.ismailmushraf.bujo.R;
import com.ismailmushraf.bujo.db.DatabaseManager;
import com.ismailmushraf.bujo.models.WorkoutSet;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class WorkoutHistoryFragment extends Fragment {

    private DatabaseManager dbManager;
    private List<Object> historyItems; // Holds HeaderItems and WorkoutSets
    private Set<String> expandedDates; // Keeps track of which dates are currently open
    private HistoryAdapter adapter;

    // Helper class for headers
    private static class HeaderItem {
        String dateStr;
        String displayText;
        HeaderItem(String dateStr, String displayText) {
            this.dateStr = dateStr;
            this.displayText = displayText;
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.fragment_workout_history, container, false);

        if (getActivity() instanceof MainActivity) {
            ((MainActivity) getActivity()).setToolbarTitle("WORKOUT HISTORY");
            ((MainActivity) getActivity()).setToolbarSubtitle("");
        }

        dbManager = new DatabaseManager(getActivity());
        dbManager.open();

        expandedDates = new HashSet<>();
        refreshData();

        ListView lvHistory = root.findViewById(R.id.lv_history);
        adapter = new HistoryAdapter();
        lvHistory.setAdapter(adapter);

        // Handle item clicks to expand/collapse headers
        lvHistory.setOnItemClickListener((parent, view, position, id) -> {
            Object item = historyItems.get(position);
            if (item instanceof HeaderItem) {
                HeaderItem header = (HeaderItem) item;
                if (expandedDates.contains(header.dateStr)) {
                    expandedDates.remove(header.dateStr);
                } else {
                    expandedDates.add(header.dateStr);
                }
                refreshData();
                adapter.notifyDataSetChanged();
            }
        });

        return root;
    }

    private void refreshData() {
        if (historyItems == null) {
            historyItems = new ArrayList<>();
        }
        historyItems.clear();
        
        List<String> dates = dbManager.getAllWorkoutDatesDescending();

        for (String date : dates) {
            long durationMs = dbManager.getSessionDuration(date);
            long minutes = (durationMs / 1000) / 60;
            
            HeaderItem header = new HeaderItem(date, date + " (Duration: " + minutes + " min)");
            historyItems.add(header);

            // Only add the workout items if this date is expanded
            if (expandedDates.contains(date)) {
                List<Object> items = dbManager.getGroupedDailyWorkouts(date);
                historyItems.addAll(items);
            }
        }
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        dbManager.close();
    }

    private class HistoryAdapter extends BaseAdapter {
        private static final int TYPE_HEADER = 0;
        private static final int TYPE_ITEM = 1;

        @Override public int getCount() { return historyItems.size(); }
        @Override public Object getItem(int position) { return historyItems.get(position); }
        @Override public long getItemId(int position) { return position; }
        @Override public int getViewTypeCount() { return 3; }
        @Override public int getItemViewType(int position) {
            Object item = historyItems.get(position);
            if (item instanceof HeaderItem) return TYPE_HEADER;
            if (item instanceof String) return 2; // For the exercise name sub-headers generated by getGroupedDailyWorkouts
            return TYPE_ITEM;
        }

        @Override
        public View getView(int position, View convertView, ViewGroup parent) {
            int type = getItemViewType(position);
            Object data = historyItems.get(position);

            if (type == TYPE_HEADER) {
                if (convertView == null) {
                    convertView = LayoutInflater.from(getActivity()).inflate(R.layout.item_workout_history_header, parent, false);
                    convertView.setBackgroundColor(getResources().getColor(R.color.bujo_divider));
                }
                
                HeaderItem header = (HeaderItem) data;
                TextView tv = convertView.findViewById(R.id.tv_history_date_header);
                android.widget.ImageView iv = convertView.findViewById(R.id.iv_history_chevron);
                
                tv.setText(header.displayText);
                
                if (expandedDates.contains(header.dateStr)) {
                    iv.setImageResource(R.drawable.ic_bb10_chevron_up);
                } else {
                    iv.setImageResource(R.drawable.ic_bb10_chevron_down);
                }
            } else if (type == 2) {
                // Exercise Name Sub-Header (e.g. "PULL-UPS (PR: 20)")
                if (convertView == null) {
                    TextView tv = new TextView(getActivity());
                    tv.setPadding(32, 16, 16, 8);
                    tv.setTextSize(14);
                    tv.setTextColor(getResources().getColor(R.color.bujo_text_secondary));
                    tv.setTypeface(null, android.graphics.Typeface.BOLD);
                    tv.setBackgroundColor(getResources().getColor(R.color.white));
                    convertView = tv;
                }
                ((TextView) convertView).setText((String) data);
            } else {
                if (convertView == null) {
                    convertView = LayoutInflater.from(getActivity()).inflate(R.layout.item_workout_set_row, parent, false);
                }

                WorkoutSet ws = (WorkoutSet) data;
                String line1 = "Round " + ws.getSetNumber() + ": " + ws.getReps() + " reps";
                if (ws.getWeight() > 0) line1 += " @ " + ws.getWeight() + " kg";

                TextView tvLine1 = convertView.findViewById(R.id.tv_set_title);
                TextView noteView = convertView.findViewById(R.id.tv_set_note);

                tvLine1.setText(line1);

                if (ws.getNote() != null && !ws.getNote().isEmpty()) {
                    noteView.setVisibility(View.VISIBLE);
                    noteView.setText("Note: " + ws.getNote());
                } else {
                    noteView.setVisibility(View.GONE);
                }
            }
            return convertView;
        }
    }
}